version: "3"
services:
  users:
    build: ./users
    restart: always
    labels:
      - "traefik.http.routers.users.rule=(Host(`app.localhost`) && PathPrefix(`/users`))"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    env_file:
      - global.env
    depends_on:
      - mysql
      - traefik

  jobs:
    build: ./jobs
    restart: always
    labels:
      - "traefik.http.routers.jobs.rule=(Host(`app.localhost`) && PathPrefix(`/jobs`))"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    env_file:
      - global.env
    depends_on:
      - mysql
      - traefik

  auth:
    build: ./auth
    restart: always
    labels:
      - "traefik.http.routers.auth.rule=(Host(`app.localhost`) && PathPrefix(`/auth`))"
    env_file:
      - global.env
    depends_on:
      - mysql
      - traefik

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  traefik:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  my-db:
