version: "3"
services:
  # frontend:
  #   build: ./frontend
  # auth:
  #   build: ./auth
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: "user"
  #     MYSQL_PASSWORD: "password"
  #     MYSQL_DB: "db"
  #     MYSQL_PORT: "3306"
  users:
    build: ./users
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mysql_db
    depends_on:
      - mysql

  jobs:
    build: ./jobs
    restart: always
    ports:
      - "5001:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mysql_db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
