version: "3"
services:
  users:
    build: ./users
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: users_db
    depends_on:
      - mysql

  jobs:
    build: ./jobs
    restart: always
    ports:
      - "5001:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: jobs_db
    env_file:
      - global.env
    depends_on:
      - mysql

  auth:
    build: ./auth
    restart: always
    ports:
      - "5002:5000"
    env_file:
      - global.env

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
